const SUPABASE_URL = 'https://gqnjkonerjhjpqlblwxp.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdxbmprb25lcmpoanBxbGJsd3hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODUyNDMxODIsImV4cCI6MjEwMDgxOTE4Mn0.c-Gbre-nxl_zxYUvGeSCXAI3DVMdB1IWxC1SX0k5r2Y';

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
